name: connections-workshop
channels:
  - conda-forge
  - anaconda
dependencies:
  - jupyter
  - scikit-learn
  - scikit-image # demo has an issue with skimage not being installed
  - pip
  - tensorflow
  - pip:
    - scivision
